<script setup lang="ts">
import { Form } from '@inertiajs/vue3';
import { useClipboard } from '@vueuse/core';
import { Check, Copy, ScanLine } from 'lucide-vue-next';
import { computed, nextTick, ref, useTemplateRef, watch } from 'vue';
import AlertError from '@/components/AlertError.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    InputOTP,
    InputOTPGroup,
    InputOTPSlot,
} from '@/components/ui/input-otp';
import { Spinner } from '@/components/ui/spinner';
import { useAppearance } from '@/composables/useAppearance';
import { useTwoFactorAuth } from '@/composables/useTwoFactorAuth';
import { confirm } from '@/routes/two-factor';
import type { TwoFactorConfigContent } from '@/types';

type Props = {
    requiresConfirmation: boolean;
    twoFactorEnabled: boolean;
};

const { resolvedAppearance } = useAppearance();

const props = defineProps<Props>();
const isOpen = defineModel<boolean>('isOpen');

const { copy, copied } = useClipboard();
const { qrCodeSvg, manualSetupKey, clearSetupData, fetchSetupData, errors } =
    useTwoFactorAuth();

const showVerificationStep = ref(false);
const code = ref<string>('');

const pinInputContainerRef = useTemplateRef('pinInputContainerRef');

const modalConfig = computed<TwoFactorConfigContent>(() => {
    if (props.twoFactorEnabled) {
        return {
            title: '2FA Enabled',
            description:
                'Two-factor authentication is now active. Scan the QR code below or enter the setup key in your authenticator app.',
            buttonText: 'Close',
        };
    }

    if (showVerificationStep.value) {
        return {
            title: 'Verify Authentication Code',
            description:
                'Please enter the 6-digit code generated by your authenticator app.',
            buttonText: 'Continue',
        };
    }

    return {
        title: 'Enable Two-Factor Security',
        description:
            'To finish enabling two-factor authentication, please scan the QR code below or enter the manual setup key into your authenticator app.',
        buttonText: 'Continue',
    };
});

const handleModalNextStep = () => {
    if (props.requiresConfirmation) {
        showVerificationStep.value = true;

        nextTick(() => {
            pinInputContainerRef.value?.querySelector('input')?.focus();
        });

        return;
    }

    clearSetupData();
    isOpen.value = false;
};

const resetModalState = () => {
    if (props.twoFactorEnabled) {
        clearSetupData();
    }

    showVerificationStep.value = false;
    code.value = '';
};

watch(
    () => isOpen.value,
    async (isOpen) => {
        if (!isOpen) {
            resetModalState();
            return;
        }

        if (!qrCodeSvg.value) {
            await fetchSetupData();
        }
    },
);
</script>

<template>
    <Dialog :open="isOpen" @update:open="isOpen = $event">
        <!-- BRANDING FIX: Changed background to brand-blush and border to brand-rose -->
        <DialogContent
            class="rounded-sm border border-brand-rose/30 bg-brand-blush p-8 shadow-2xl sm:max-w-md sm:p-10"
        >
            <DialogHeader
                class="mb-6 flex flex-col items-center justify-center"
            >
                <div
                    class="mb-6 w-auto rounded-full bg-brand-light p-1 shadow-sm"
                >
                    <div
                        class="relative overflow-hidden rounded-full border border-brand-rose/20 bg-white p-3"
                    >
                        <ScanLine
                            class="relative z-20 size-6 text-brand-wine"
                        />
                    </div>
                </div>

                <!-- BRANDING FIX: Luxury Typography -->
                <DialogTitle
                    class="mb-3 text-center font-serif text-3xl font-normal text-brand-wine"
                >
                    {{ modalConfig.title }}
                </DialogTitle>

                <DialogDescription
                    class="mx-auto max-w-sm text-center text-sm leading-relaxed font-light text-brand-wine/70"
                >
                    {{ modalConfig.description }}
                </DialogDescription>
            </DialogHeader>

            <div
                class="relative flex w-auto flex-col items-center justify-center space-y-8"
            >
                <template v-if="!showVerificationStep">
                    <AlertError v-if="errors?.length" :errors="errors" />
                    <template v-else>
                        <!-- QR Code Frame -->
                        <div
                            class="relative mx-auto flex max-w-md items-center overflow-hidden"
                        >
                            <div
                                class="relative mx-auto aspect-square w-56 overflow-hidden rounded-md border border-brand-rose/30 bg-white shadow-sm"
                            >
                                <div
                                    v-if="!qrCodeSvg"
                                    class="absolute inset-0 z-10 flex aspect-square h-auto w-full animate-pulse items-center justify-center bg-brand-light/50"
                                >
                                    <Spinner
                                        class="size-6 text-brand-wine/30"
                                    />
                                </div>
                                <div
                                    v-else
                                    class="relative z-10 overflow-hidden p-4"
                                >
                                    <div
                                        v-html="qrCodeSvg"
                                        class="flex aspect-square size-full items-center justify-center"
                                        :style="{
                                            filter:
                                                resolvedAppearance === 'dark'
                                                    ? 'invert(1) brightness(1.5)'
                                                    : undefined,
                                        }"
                                    />
                                </div>
                            </div>
                        </div>

                        <!-- Manual Key Box -->
                        <div
                            class="flex w-full flex-col gap-4 border-t border-brand-rose/20 pt-4"
                        >
                            <p
                                class="text-center text-[0.65rem] font-semibold tracking-widest text-brand-wine/50 uppercase"
                            >
                                Or enter manual setup key
                            </p>

                            <div
                                class="flex w-full items-stretch overflow-hidden rounded-sm border border-brand-rose/30 bg-white shadow-inner"
                            >
                                <div
                                    v-if="!manualSetupKey"
                                    class="flex h-12 w-full items-center justify-center bg-brand-light/30"
                                >
                                    <Spinner
                                        class="h-4 w-4 text-brand-wine/30"
                                    />
                                </div>
                                <template v-else>
                                    <!-- BRANDING FIX: Beautiful Input -->
                                    <input
                                        type="text"
                                        readonly
                                        :value="manualSetupKey"
                                        class="h-full w-full bg-transparent p-3 text-center font-mono text-sm text-brand-wine focus:outline-none"
                                    />
                                    <button
                                        @click="copy(manualSetupKey || '')"
                                        class="relative flex h-auto items-center justify-center border-l border-brand-rose/30 bg-brand-light/30 px-4 transition-colors hover:bg-brand-rose/20"
                                        title="Copy Key"
                                    >
                                        <Check
                                            v-if="copied"
                                            class="h-4 w-4 text-brand-rose"
                                        />
                                        <Copy
                                            v-else
                                            class="h-4 w-4 text-brand-wine/60"
                                        />
                                    </button>
                                </template>
                            </div>
                        </div>

                        <div
                            class="flex w-full items-center justify-center pt-2"
                        >
                            <!-- BRANDING FIX: Primary Button Style -->
                            <button
                                @click="handleModalNextStep"
                                class="w-full rounded-sm bg-brand-wine px-8 py-3 text-[0.65rem] font-bold tracking-[0.2em] text-brand-light uppercase shadow-md transition-all hover:bg-brand-rose"
                            >
                                {{ modalConfig.buttonText }}
                            </button>
                        </div>
                    </template>
                </template>

                <template v-else>
                    <Form
                        v-bind="confirm.form()"
                        error-bag="confirmTwoFactorAuthentication"
                        reset-on-error
                        @finish="code = ''"
                        @success="isOpen = false"
                        v-slot="{ errors, processing }"
                        class="w-full"
                    >
                        <input type="hidden" name="code" :value="code" />

                        <div
                            ref="pinInputContainerRef"
                            class="relative w-full space-y-8"
                        >
                            <!-- PIN Input Container -->
                            <div
                                class="flex w-full flex-col items-center justify-center space-y-4"
                            >
                                <InputOTP
                                    id="otp"
                                    v-model="code"
                                    :maxlength="6"
                                    :disabled="processing"
                                >
                                    <!-- Using Shadcn OTP Group but we will inject custom CSS below to style it -->
                                    <InputOTPGroup class="custom-otp-group">
                                        <InputOTPSlot
                                            v-for="index in 6"
                                            :key="index"
                                            :index="index - 1"
                                            class="custom-otp-slot"
                                        />
                                    </InputOTPGroup>
                                </InputOTP>
                                <InputError
                                    :message="errors?.code"
                                    class="text-xs text-red-500"
                                />
                            </div>

                            <div
                                class="flex w-full items-center gap-4 border-t border-brand-rose/20 pt-8"
                            >
                                <button
                                    type="button"
                                    @click="showVerificationStep = false"
                                    :disabled="processing"
                                    class="flex-1 rounded-sm border border-brand-rose/50 px-6 py-3 text-[0.65rem] font-bold tracking-[0.2em] text-brand-wine uppercase transition-all hover:bg-brand-light disabled:opacity-50"
                                >
                                    Back
                                </button>
                                <button
                                    type="submit"
                                    :disabled="processing || code.length < 6"
                                    class="flex-1 rounded-sm bg-brand-wine px-6 py-3 text-[0.65rem] font-bold tracking-[0.2em] text-brand-light uppercase shadow-md transition-all hover:bg-brand-rose disabled:opacity-50"
                                >
                                    Confirm
                                </button>
                            </div>
                        </div>
                    </Form>
                </template>
            </div>
        </DialogContent>
    </Dialog>
</template>

<style>
/* Override the Shadcn OTP input boxes to match the luxury brand */
.custom-otp-group {
    gap: 0.5rem;
}

.custom-otp-slot {
    width: 3rem !important;
    height: 3.5rem !important;
    border: 1px solid rgba(205, 159, 174, 0.4) !important; /* brand-rose */
    border-radius: 0.25rem !important;
    background-color: #ffffff;
    font-size: 1.5rem !important;
    color: #5a182c !important; /* brand-wine */
    font-family: 'Montserrat', sans-serif !important;
    transition: all 0.3s ease;
}

.custom-otp-slot:focus-within {
    border-color: #5a182c !important;
    box-shadow: 0 0 0 1px #5a182c !important;
}
</style>
